version: '3'

services:
  nuxt:
    build:
      context: ./
      dockerfile: ./project/Dockerfile
    working_dir: /app/project
    tty: true
    command: yarn run dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
